### ISSUE TITLE
Merging blocked by branch protection

### ISSUE THREAD

**Issue by rarkins** [uber-workflow/probot-app-merge-pr#13]
Hi, I noticed you had installed Renovate on these repositories - awesome. I wanted to get your take on a problem I've found with Renovate's own "automerge" feature. GitHub have a limitation where if an organisation has defined a list of users and/or teams who can push to `master`, then apps like `renovate` or `fusion-bot` are then prevented from merging, regardless of their read/write permissions. This is because there's no way to add an *app* via that UI.

I assume you are affected too - have you noticed that?

The issue in Renovate is here: https://github.com/renovateapp/renovate/issues/846
The (nearly one year old!) report to GitHub is here: https://platform.github.community/t/repositories-which-have-protected-branches-with-push-restrictions-have-no-ability-to-grant-push-rights-to-integrations/1376

If you are also affected, it would be great it you can add your voice to the app forum. I don't know why GitHub refuse to prioritise a fix.

**Comment by KevinGrandon** [comment]
Hello, thanks for chiming in. Yes we are currently impacted by this. Hoping that the github will fix this eventually, but in the meantime we're looking at solving this in a few ways.

One way might be to have a token available to our probot which will add a review for any PR submitted by the renovate bot. Hopefully Github fixes this so that we won't have to do this work. We'll leverage our network here to see if there's folks at Github we can reach out to.

**Comment by rarkins** [comment]
I think a fusion bot feature to (selectively) approve PRs from other bots would be neat. My "renovate-approve" bot today just approves 100% of renovate's PRs, however I can see a scenario where people might want to configure it so the auto-approves are only for patch and minor while major updates should always have a human reviewer.

So having fusion approve Renovate is perhaps a good solution, because I'm not sure there's anything for GitHub to fix. Also, GitHub's required reviews feature can also be a nice way to gate Renovate's automerges, e.g. as an alternative to "!merge".

The push restriction branch protection problem is the one with no workaround, i.e. when you enable this:

> **Restrict who can push to this branch**
Specify people or teams allowed to push to this branch. Required status checks will still prevent these people from merging if the checks fail.

Because it's impossible to specify an app/bot with the current UI, it then becomes impossible for the app to ever push to master (whether branch push or PR merging).
