### ISSUE TITLE
Delete branch if it exists

### ISSUE THREAD

**Issue by KevinGrandon** [uber-workflow/probot-app-merge-pr#45]
Sometimes a core contributor will open a pull request from a branch, we should delete the branch if it exists to clean up the current list of branches.

**Comment by swojit** [comment]
Or we can use another app? https://github.com/apps/delete-branch-after-pr-merge

**Comment by KevinGrandon** [comment]
(no longer necessary since we have https://github.com/uber-workflow/probot-app-delete-merged-branch now)
